export const massageInput = document.querySelector('.header__textarea');
export const countCharacters = document.querySelector('.count-characters');
export const limitCharacters = document.querySelector('.count-limit');
export const checkboxTransliterate = document.querySelector('.massage__input');
export const massageForm = document.querySelector('.massage');
export const url = './ajax/newMassage.php';
export const login = 'W4MpbAZCihp4DBLIKn1XTzUh';
export const symbols = [
    ["а", "a"],
    ["А", "A"],
    ["б", "b"],
    ["Б", "B"],
    ["в", "v"],
    ["В", "V"],
    ["г", "g"],
    ["Г", "G"],
    ["д", "d"],
    ["Д", "D"],
    ["е", "e"],
    ["Е", "E"],
    ["ё", "yo"],
    ["Ё", "Yo"],
    ["ж", "zh"],
    ["Ж", "Zh"],
    ["з", "z"],
    ["З", "Z"],
    ["и", "i"],
    ["И", "I"],
    ["й", "y"],
    ["Й", "Y"],
    ["к", "k"],
    ["К", "K"],
    ["л", "l"],
    ["Л", "L"],
    ["м", "m"],
    ["М", "M"],
    ["н", "n"],
    ["Н", "N"],
    ["о", "o"],
    ["О", "O"],
    ["п", "p"],
    ["П", "P"],
    ["р", "r"],
    ["Р", "R"],
    ["с", "s"],
    ["С", "S"], 
    ["т", "t"],
    ["Т", "T"],
    ["у", "u"],
    ["У", "U"],
    ["ф", "f"],
    ["Ф", "F"],
    ["х", "h"],
    ["Х", "H"],
    ["ц", "ts"],
    ["Ц", "Ts"],
    ["ч", "ch"],
    ["Ч", "Ch"],
    ["ш", "sh"],
    ["Ш", "Sh"],
    ["щ", "sch"],
    ["Щ", "Sch"],
    ["ъ", "'"],
    ["Ъ", "'"],
    ["ы", "i"],
    ["Ы", "I"],
    ["ь", "'"],
    ["Ь", "'"],
    ["э", "e"],
    ["Э", "E"],
    ["ю", "u"],
    ["Ю", "U"],
    ["я", "ya"],
    ["Я", "Ya"], 
    ["«", '"'],
    ["»", '"'],
    ["–", "-"],
    ["—", "-"],
    ["№", "#"],
    ["`", "'"],
];